### PR TITLE
Admin Dashboard - Collapsible Details View

### PR DESCRIPTION
**Pull request by NarekA**
I made this PR to see if this feature would be useful for other people. Right now, you can't see all of a user or server's details in the admin page so I added a collapsible view which will let you see the entire server and user objects. I'm open to ideas about how the information is displayed. Will add more tests if this feature is accepted.

improved-collapse

### CODE REVIEW

**Comment by NarekA** [comment]
@minrk @consideRatio How do you guys feel about merging this feature?

**Comment by minrk** [comment]
It seems pretty nice, to me! I'd like feedback from @naatebarber or @ykazakov

**Comment by ykazakov** [comment]
This is interesting. Particularly quickly seeing all groups of the user could be useful.
What happens if the user has started several (named) severs? 
I think the panel could be a bit too crowded for displaying many tables. What if to put this information in tooltips, separately for each user and server?

**Comment by NarekA** [comment]
@ykazakov we currently have one row per server so it won't show more than one server at a time.

**Comment by ykazakov** [comment]
@NarekA can you provide a screenshot with multiple servers like in #3790? I thought that the details view is per user, not per server.

**Comment by NarekA** [comment]
@ykazakov I modified the layout a bit to make it scale better to servers with a large states
Screen Shot 2022-03-21 at 12 56 24 PM

**Comment by ykazakov** [comment]
Looks good to me! My only concern is that someone would need to maintain this UI if hub API changes. ;-) 

I wonder if for the debugging scenario mentioned by @johnkpark, a better solution would be to use [REST API](https://jupyterhub.readthedocs.io/en/stable/reference/rest.html) to access the user and server details. This can be easily done using  a notebook [like this one](https://gist.github.com/minrk/1940060144e7ae2717f57018d4964769). One can even make some nice UI using pandas and javascript to display the data in tables and use buttons and layout similar to the Admin menu. We use similar notebooks to manage users via nbgrader api.

**Comment by NarekA** [comment]
@minrk Can we merge this?

**Comment by minrk** [comment]
Thanks @NarekA and @ykazakov for the review!

**Pull request merged**
