### PR TITLE
add dark mode toggle

### PR DESCRIPTION
**Pull request by minrk**
continues #4878 but adds 

- toggle button in upper right instead of server setting
- system dark-mode is respected by default
- explicit setting is remembered in `localStorage["jupyterhub-bs-theme"]`
- `btn-contrast` classes are added to allow buttons to be dark-on-light and light-on-dark via css

cc @benz0li

https://github.com/user-attachments/assets/a1aa8180-304d-487b-bc12-05cca1c0adc0

### CODE REVIEW

**Comment by benz0li** [comment]
@minrk Perfect!

Many thanks.

**Comment by benz0li** [comment]
@minrk https://jupyterhub.readthedocs.io/en/stable/ has a toggle, too. Handling seems a little different, though.

**Comment by benz0li** [comment]
Cross reference:

* https://github.com/pydata/pydata-sphinx-theme/pull/540

**Comment by benz0li** [comment]
@minrk I am happy with your solution, too.

It would be great if this could be merged soon.

**Comment by minrk** [comment]
Thanks @benz0li!

**Pull request merged**
