### PR TITLE
changelog for 5.1.0

### PR DESCRIPTION
**Pull request by minrk**
small release; a few nice new config options and one performance regression fix

trying to keep releases small and more frequent

### CODE REVIEW

**Review by manics — APPROVED** [review]
LGTM.

Is there a quick-fix for https://github.com/jupyterhub/jupyterhub/issues/4845 ? If so it'd be nice to get that in, and save the effort of making another patch release.

**Comment by minrk** [comment]
I'll have a look at that tomorrow

**Comment by krassowski** [comment]
I'm not quite sure if my diagnosis of that issue was correct, I would not want to block you on this or take up your time folks. I will get back to it as soon as I can.

**Comment by minrk** [comment]
I'm in no rush to release, I'd like to have a good answer either way, whether it's docs or a bug fix in JupyterHub or even in JupyterLab.

**Comment by yuvipanda** [comment]
Just wanted to check back on this :)

**Comment by minrk** [comment]
I ran out of time to finish up one last thing before vacation, I'll do this next week when I get back.

**Pull request merged**
