### PR TITLE
Spawner.py: do not quote Popen args

### PR DESCRIPTION
**Pull request by adelcast**
On Windows, Popen calls list2cmdline, which makes sure quotes are added
if needed. Currently, double quoting is happening, which breaks options
like notebook_dir, when full paths are used.

Signed-off-by: Alejandro del Castillo <alejandro.delcastillo@ni.com>

### CODE REVIEW

**Comment by minrk** [comment]
Unfortunately, it's important that the quotes are preserved on the command-line (double-quotes is intended here) due to weirdness in traitlets handling cli arguments that could look like numbers. What's going wrong when quoting paths on Windows?

**Comment by adelcast** [comment]
With quotes this is how my spawning looks like:

[I 2018-12-04 13:43:09.771 JupyterHub winlocalprocessspawner:55] Spawning 'C:\Python\3.6\python.exe' -m jupyterhub.singleuser --port=38730 '--notebook-dir="C:\ProgramData\notebooks"' '--NotebookApp.default_url="/lab"' --show-control-btn=True '--config=C:\Program Files\\Shared\\Jupyterhub\jupyter_notebook_config.py'

and the error:

[C 2018-12-04 13:43:10.998 SingleUserNotebookApp application:91] No such notebook dir: 'C:\\Program Files\\Shared\\Jupyterhub\\"C:\\ProgramData\\notebooks"'

Popen processes the args via the function list2cmdline, which takes care of adding quotes when needed. My understanding is that you don't quote since Popen will do that for you. Since Popen is receiving a list, it already knows where to put the quotes, as each element on the list represents one argument.

I could change the PR to have a Windows case that removes the quotes.

**Comment by minrk** [comment]
Even on Windows, though, it is important that some of these get quotes added, we just might not be adding them correctly. Perhaps you can replace `"%s"` with `%r`?

**Comment by adelcast** [comment]
Doesn't work either. As I mentioned above, this has to do with the way Popen works. Inside Popen, it calls list2cmdline, to create the correct cmd line. I printed a dump of subprocess.list2cmdline(cmd) and got:

"C:\Program Files\National Instruments\Shared\Skyline\Python\3.6\python.exe" -m jupyterhub.singleuser --port=7310 "--notebook-dir=\"C:\ProgramData\National Instruments\Skyline\JupyterHub\notebooks\"" --NotebookApp.default_url=\"/lab\" --show-control-btn=True "--config=C:\Program Files\National Instruments\Shared\Skyline\Jupyterhub\jupyter_notebook_config.py"

Running this exact line fails, since --notebook-dir has the extra quotes, which trip many things down the line (determining if a path is absolute  or not, etc). 

Another option would be to remove the quotes, if present, inside _notebook_dir_validate in singleuser.py. I just tried it and it works. Would that be acceptable?

**Comment by minrk** [comment]
If you did repr, the line would be `--notebook-dir="C:\\ProgramData...` wouldn't it?

I don't like the double-quoting, but it is necessary for certain fields that could be valid numbers. Maybe we can do a better job and protect against the few cases where that could happen and revert the extra encoding.

Can you add this:

```python
import ast
def _quote_safe(s):
    """pass a string that is safe on the command-line

    traitlets may parse literals on the command-line, e.g. `--ip=123` will be the number 123 instead of the *string* 123.
    wrap valid literals in repr to ensure they are safe
    """

    try:
        val = ast.literal_eval(s)
    except Exception:
        # not valid, leave it alone
        return s
    else:
        # it's a valid literal, wrap it in repr (usually just quotes, but with proper escapes)
        # to avoid getting interpreted by traitlets
        return repr(s)
```

and pass the strings through this function? It should result in no quotes most of the time, but apply the safe wrapping in the edge cases where we need to.

**Comment by adelcast** [comment]
Sorry for the late reply, but I was out last week.

The plain repr adds the problematic double escaping: "--notebook-dir=\"'C:\\ProgramData\\National Instruments\\Skyline\\JupyterHub\\notebooks'\""....

However, using your more generic solution, the problem was solved! I like your solution a whole lot more since it is specifically fixing the traitlets issue (adding quotes when traitlets may get confused). How do you want to move forward with this? Close this PR then add the _quote_safe function on another one?

**Comment by minrk** [comment]
If you'd like to update the PR to add and use `_quote_safe`, I'm happy to merge it.

**Comment by adelcast** [comment]
ok, just updated the PR

**Comment by minrk** [comment]
Thanks!

**Pull request merged**
