### PR TITLE
Expand ~ before quoting notebook_dir

### LINKED ISSUE #878: notebooks_dir ~ expands incorrectly
**How to reproduce the issue**

Configure jupyterhub 0.7.0b1 with:

```
c.SudoSpawner.sudospawner_path = "/some/where/bin/sudospawner"
c.SudoSpawner.sudo_args = ['-nH']
c.Spawner.notebook_dir = '~/notebooks'
```

Try to login. Notebook server startup logs:

```
[C 2016-11-21 12:32:15.936 SingleUserNotebookApp application:91] No such notebook dir: '/home/pparente/~/notebooks'
```

**What you expected to happen**

Path should be expanded properly.

**What actually happens**

Path is expanded but also gets the ~ part tacked back on.

**Share what version of JupyterHub you are using**

0.7.0b1

I put a print in the jupyterhub-singleuser script and confirmed that it is receiving `--notebook-dir="~/notebooks"` as in `sys.argv`. So it appears the incorrect expansion is happening somewhere after that.

### PR DESCRIPTION
**Pull request by parente**
closes #878

### CODE REVIEW

**Comment by parente** [comment]
Don't merge quite yet. Testing a bit.

**Comment by parente** [comment]
Nope. Expands too early for sudospawner.

**Comment by parente** [comment]
Restoring the original, unquoted `--notebook_dir=%s` template in spawner.py fixes the ~ expansion bug. It's questionable whether this is trading one fix for other problems, however.

**Comment by minrk** [comment]
I think this is a bug for the single-user server to fix (by calling `expanduser`), and not to change here. The reason to not change it here is that the quotes were added to deal with an issue in traitlets CLI parsing, to ensure the result is a string (i.e. adding quotes shouldn't change the value).

I also don't think the shell expansion will work for Spawners that launch without instantiating a shell (`shell=True` for Popen), because raw command-launching doesn't expand `~` (I think).

**Comment by willingc** [comment]
Thanks @parente and @minrk :D

**Pull request closed without merging**
