### PR TITLE
Accessibility:-Added eslint-plugin-jsx-a11y package as linter for accessibility

### PR DESCRIPTION
**Pull request by Biki-das**
Adding a linter for accessibility can really help us to catch static code errors in regards to accessibility , This PR adds the Eslint-plugin-jsx-a11y package and also set the config for the same.

### CODE REVIEW

**Comment by liliyao2022** [comment]
Hey @Biki-das, after doing some research, I found out that you used the wrong package name,  it should be "eslint-plugin-jsx-a11y", instead of "eslint-plugin-jsx-ally".

**Comment by liliyao2022** [comment]
> Hey @Biki-das, after doing some research, I found out that you used the wrong package name, it should be "eslint-plugin-jsx-a11y", instead of "eslint-plugin-jsx-ally" in your title.

**Comment by Biki-das** [comment]
> Hey @Biki-das, after doing some research, I found out that you used the wrong package name, it should be "eslint-plugin-jsx-a11y", instead of "eslint-plugin-jsx-ally".

yeah i made the mistake in the PR name, rest the package is a valid one and it works as i have already set the config for the same in the .eslint.rc.json file

**Comment by minrk** [comment]
Accessibility testing is being discussed in #4078. We should resolve that discussion about how to approach accessibility testing, what tools to use, and how to integrate it with CI before proceeding with implementation.

**Comment by Biki-das** [comment]
> Accessibility testing is being discussed in #4078. We should resolve that discussion about how to approach accessibility testing, what tools to use, and how to integrate it with CI before proceeding with implementation.

thanks for the review!, yes as you said it will require a proper discussion on what approach we would be taking to deal with accessibility testing

**Comment by minrk** [comment]
Thanks for the PR! Closing due to conflicts, pending resolution of tool selection in #4078.

**Pull request closed without merging**
