### PR TITLE
Add AWS setup documentation.

### PR DESCRIPTION
**Pull request by ThomasMChen**
Add markdown documentation for setting up AWS EC2 instance for JupyterHub with NGINX and Docker. Elaborates on AWS process and includes screenshots as well as AMI and Security Group settings documentation.

### CODE REVIEW

**Comment by ThomasMChen** [comment]
Written in collaboration with @patnir

**Comment by willingc** [comment]
Hi @ThomasMChen and @patnir, Thanks! It was great working with you. I'll review this tomorrow and get it merged :-)

**Comment by willingc** [comment]
Thanks @ThomasMChen and @patnir for your good work at Hack Illinois. Hope to see future contributions too.

**Comment by patnir** [comment]
No problem! Thank you for all the help and advice @willingc !!!

**Pull request merged**
