### PR TITLE
add HUNT into research institutions

### PR DESCRIPTION
**Pull request by matuskosut**
Hi all,

I would like to add HUNT into the list of research institutions. We are providing virtual labs with Jupyterhub deployments for students, researchers, and institutions working with sensitive data in Norway but also internationally. You can find more info on our profile https://github.com/huntdatacenter#welcome-to-hunt-cloud or feel free to ask me.

Is there other specific requirements for adding an institution to the list?

### CODE REVIEW

**Comment by minrk** [comment]
I think it's fine to add you. It seems like the 'institution' ought to be NTNU instead of HUNT, is that right?

:wave: from Oslo

**Comment by matuskosut** [comment]
Hi @minrk 

we were aiming for recognition of HUNT. I see it similar to _Minnesota Supercomputing Institute_ being listed on behalf of _University of Minnesota_. HUNT is well known in health research as one of the largest cohort studies in the world. And here we come into the play by providing virtual labs for working with sensitive data (health data being one of the most sensitive) to many institutions in Norway and abroad. As HUNT/HUNT Cloud we are also iso certified and typically we do not provide these labs for general research (non-sensitive data).

Do you travel up north sometimes? You should definitely stop by for a chat if you happen to be in Trondheim. We would be happy to share a bit about our work.

**Comment by manics** [comment]
@matuskosut that sounds really cool! I hadn't heard of HUNT before but I'm interested to hear more about how you're using JupyterHub (and everything else) with sensitive data- I'm in the UK working with trusted research environments.

**Comment by matuskosut** [comment]
@manics cool, we are also in on TREs! PMed you OOB.

**Comment by minrk** [comment]
Fair enough, thanks!

I don't get up often, but have visited a few years ago.

**Pull request merged**
