### PR TITLE
Update App.jsx for react 18

### PR DESCRIPTION
**Pull request by liliyao2022**
updated the code to React 18.

### CODE REVIEW

**Comment by minrk** [comment]
Is this replacing #4149? You do not need to open new pull requests to make further changes. The webpack build is failing with a SyntaxError on `as HTMLElement`. Perhaps you were expecting typescript? This is javascript, not typescript.

**Comment by liliyao2022** [comment]
Hi, I know it is Javascript and I have deleted #4149. I was trying to Upgrade the code to React 18, however, it seemed to fail, I'll try to work on it tomorrow. Thanks!

**Comment by minrk** [comment]
Thanks for your contribution!

If you don’t plan to finish this PR since the outreachy contribution period has ended, let us know and we will take over the remaining issues. If we don’t hear from you, we may close the PR. Don’t worry, PRs can always be reopened, if you want to come back and finish it!

**Comment by minrk** [comment]
Thanks for your PR! I'm closing this for inactivity, but it can always be re-opened if someone wants to come back and finish it.

**Pull request closed without merging**
