### PR TITLE
changelog for 1.5.1

### PR DESCRIPTION
**Pull request by minrk**
just backporting the db fix (#4076)

cc @mriedem

### CODE REVIEW

**Review by mriedem — APPROVED** [review]
lgtm, thanks!

**Comment by consideRatio** [comment]
Nice LGTM! There is an action point remaining to update the changelog in the main branch as well now right?

I'm on mobile on a bus so i'll not go for that now myself.

**Comment by minrk** [comment]
Yes, adding it to #4232 as you suggested makes sense.

**Comment by minrk** [comment]
1.5.1 is published.

**Pull request merged**
