### PR TITLE
Add Missing Features In Admin Console

### LINKED ISSUE #3745: No links to access the users notebooks from the Admin menu
### Bug description

Happy New Year!

I am trying to [enable admin access to user notebooks](https://jupyterhub.readthedocs.io/en/2.0.1/getting-started/authenticators-users-basics.html#give-admin-access-to-other-users-notebook-servers-admin-access):

```
JupyterHub.admin_access = True
```

#### Expected behaviour

As of Jupyterhub 1.5.0, I could access the users notebooks from the Admin menu:

Screenshot 2022-01-01 at 23 04 24

#### Actual behaviour

As of Jupyterhub 2.0.1, there is no link for accessing the users notebooks any longer:

Screenshot 2022-01-01 at 23 05 54

However, I could still access the user notebook by entering the url manually: `127.0.0.1:8000/user/zoe/`

### How to reproduce

1. Create the files with the following contents:
  - `Dockerfile`:
```
FROM jupyterhub/jupyterhub:2.0.1

RUN pip install jupyter jupyterlab --no-cache-dir \
    && useradd -m mal \
    && useradd -m zoe

COPY jupyterhub_config.py /etc/jupyterhub/

CMD jupyterhub -f /etc/jupyterhub/jupyterhub_config.py --debug
```
  - `jupyterhub_config.py`:
```
c.Authenticator.allowed_users = {'mal', 'zoe'}
c.Authenticator.admin_users = {'mal'}
c.JupyterHub.admin_access = True

c.JupyterHub.authenticator_class = 'dummy'
c.JupyterHub.spawner_class = 'simple'
c.Spawner.args = ["--allow-root"]
```
2. Create and run the docker container:
```
docker build -t jupyterhub-adminaccess . 
docker run -it -p 8000:8000 jupyterhub-adminaccess
```
3. Open the url: `http://127.0.0.1:8000/admin`
4. Enter Username: `mal` and press "Sign in"
5. Press "Start Server" next to `zoe`

### Your personal set up

- OS: MacOS 12.1
 - Version(s):
```
% docker --version    
Docker version 20.10.11, build dea9396
```

<details><summary>Logs</summary>

```
% docker run -it -p 8000:8000 jupyterhub-adminaccess
[D 2022-01-01 22:28:32.152 JupyterHub application:731] Looking for /etc/jupyterhub/jupyterhub_config in /srv/jupyterhub
[D 2022-01-01 22:28:32.153 JupyterHub application:753] Loaded config file: /etc/jupyterhub/jupyterhub_config.py
[I 2022-01-01 22:28:32.208 JupyterHub app:2766] Running JupyterHub version 2.0.1
[I 2022-01-01 22:28:32.208 JupyterHub app:2796] Using Authenticator: jupyterhub.auth.DummyAuthenticator-2.0.1
[I 2022-01-01 22:28:32.209 JupyterHub app:2796] Using Spawner: jupyterhub.spawner.SimpleLocalProcessSpawner-2.0.1
[I 2022-01-01 22:28:32.210 JupyterHub app:2796] Using Proxy: jupyterhub.proxy.ConfigurableHTTPProxy-2.0.1
[D 2022-01-01 22:28:32.229 JupyterHub app:1646] Generating new cookie_secret
[I 2022-01-01 22:28:32.231 JupyterHub app:1651] Writing cookie_secret to /srv/jupyterhub/jupyterhub_cookie_secret
[D 2022-01-01 22:28:32.232 JupyterHub app:1773] Connecting to db: sqlite:///jupyterhub.sqlite
[D 2022-01-01 22:28:32.284 JupyterHub orm:924] Stamping empty database with alembic revision 833da8570507
[I 2022-01-01 22:28:32.293 alembic.runtime.migration migration:201] Context impl SQLiteImpl.
[I 2022-01-01 22:28:32.293 alembic.runtime.migration migration:204] Will assume non-transactional DDL.
[I 2022-01-01 22:28:32.330 alembic.runtime.migration migration:615] Running stamp_revision  -> 833da8570507
[D 2022-01-01 22:28:32.332 alembic.runtime.migration migration:815] new branch insert 833da8570507
[I 2022-01-01 22:28:32.566 JupyterHub proxy:496] Generating new CONFIGPROXY_AUTH_TOKEN
[D 2022-01-01 22:28:32.567 JupyterHub app:2019] Loading roles into database
[D 2022-01-01 22:28:32.628 JupyterHub roles:449] Assigning default role to User mal
[I 2022-01-01 22:28:32.643 JupyterHub roles:365] Adding role admin for User: mal
[I 2022-01-01 22:28:32.661 JupyterHub roles:365] Adding role user for User: mal
[D 2022-01-01 22:28:32.686 JupyterHub app:2278] Purging expired APITokens
[D 2022-01-01 22:28:32.699 JupyterHub app:2278] Purging expired OAuthCodes
[D 2022-01-01 22:28:32.708 JupyterHub app:2111] Loading role assignments from config
[D 2022-01-01 22:28:32.712 JupyterHub app:2182] Assigning 2 allowed_users to the user role
[I 2022-01-01 22:28:32.741 JupyterHub roles:365] Adding role user for User: zoe
[D 2022-01-01 22:28:32.770 JupyterHub app:2424] Initializing spawners
[D 2022-01-01 22:28:32.779 JupyterHub app:2555] Loaded users:
    
[I 2022-01-01 22:28:32.780 JupyterHub app:2835] Initialized 0 spawners in 0.011 seconds
[W 2022-01-01 22:28:32.789 JupyterHub proxy:687] Running JupyterHub without SSL.  I hope there is SSL termination happening somewhere else...
[I 2022-01-01 22:28:32.789 JupyterHub proxy:691] Starting proxy @ http://:8000
[D 2022-01-01 22:28:32.790 JupyterHub proxy:692] Proxy cmd: ['configurable-http-proxy', '--ip', '', '--port', '8000', '--api-ip', '127.0.0.1', '--api-port', '8001', '--error-target', 'http://127.0.0.1:8081/hub/error']
[D 2022-01-01 22:28:32.804 JupyterHub proxy:610] Writing proxy pid file: jupyterhub-proxy.pid
22:28:33.573 [ConfigProxy] info: Proxying http://*:8000 to (no default)
22:28:33.580 [ConfigProxy] info: Proxy API at http://127.0.0.1:8001/api/routes
[D 2022-01-01 22:28:33.682 JupyterHub proxy:728] Proxy started and appears to be up
[D 2022-01-01 22:28:33.685 JupyterHub proxy:821] Proxy: Fetching GET http://127.0.0.1:8001/api/routes
22:28:33.719 [ConfigProxy] info: 200 GET /api/routes 
[I 2022-01-01 22:28:33.719 JupyterHub app:3084] Hub API listening on http://127.0.0.1:8081/hub/
[D 2022-01-01 22:28:33.721 JupyterHub proxy:343] Fetching routes to check
[D 2022-01-01 22:28:33.721 JupyterHub proxy:821] Proxy: Fetching GET http://127.0.0.1:8001/api/routes
22:28:33.725 [ConfigProxy] info: 200 GET /api/routes 
[D 2022-01-01 22:28:33.728 JupyterHub proxy:346] Checking routes
[I 2022-01-01 22:28:33.728 JupyterHub proxy:431] Adding route for Hub: / => http://127.0.0.1:8081
[D 2022-01-01 22:28:33.730 JupyterHub proxy:821] Proxy: Fetching POST http://127.0.0.1:8001/api/routes/
22:28:33.741 [ConfigProxy] info: Adding route / -> http://127.0.0.1:8081
22:28:33.743 [ConfigProxy] info: Route added / -> http://127.0.0.1:8081
22:28:33.744 [ConfigProxy] info: 201 POST /api/routes/ 
[I 2022-01-01 22:28:33.748 JupyterHub app:3150] JupyterHub is now running at http://:8000
[D 2022-01-01 22:28:33.750 JupyterHub app:2759] It took 1.606 seconds for the Hub to start
[I 2022-01-01 22:28:38.340 JupyterHub log:189] 302 GET /admin -> /hub/admin (@::ffff:172.17.0.1) 5.45ms
[W 2022-01-01 22:28:38.394 JupyterHub base:391] Invalid or expired cookie token
[I 2022-01-01 22:28:38.398 JupyterHub log:189] 302 GET /hub/admin -> /hub/login?next=%2Fhub%2Fadmin (@::ffff:172.17.0.1) 4.44ms
[I 2022-01-01 22:28:38.516 JupyterHub log:189] 200 GET /hub/login?next=%2Fhub%2Fadmin (@::ffff:172.17.0.1) 64.76ms
[D 2022-01-01 22:28:38.799 JupyterHub log:189] 304 GET /hub/static/css/style.min.css.map (@::ffff:172.17.0.1) 10.51ms
[D 2022-01-01 22:28:46.584 JupyterHub roles:449] Assigning default role to User mal
[D 2022-01-01 22:28:46.603 JupyterHub base:561] Setting cookie for mal: jupyterhub-hub-login
[D 2022-01-01 22:28:46.605 JupyterHub base:557] Setting cookie jupyterhub-hub-login: {'httponly': True, 'path': '/hub/'}
[I 2022-01-01 22:28:46.606 JupyterHub base:797] User logged in: mal
[I 2022-01-01 22:28:46.616 JupyterHub log:189] 302 POST /hub/login?next=%2Fhub%2Fadmin -> /hub/admin (mal@::ffff:172.17.0.1) 62.05ms
[D 2022-01-01 22:28:46.679 JupyterHub base:279] Recording first activity for <User(mal 0/1 running)>
[D 2022-01-01 22:28:46.716 JupyterHub scopes:488] Checking access via scope admin:users
[D 2022-01-01 22:28:46.717 JupyterHub scopes:386] Unrestricted access to /hub/admin via admin:users
[D 2022-01-01 22:28:46.718 JupyterHub scopes:488] Checking access via scope admin:servers
[D 2022-01-01 22:28:46.718 JupyterHub scopes:386] Unrestricted access to /hub/admin via admin:servers
[D 2022-01-01 22:28:46.753 JupyterHub user:347] Creating <class 'jupyterhub.spawner.SimpleLocalProcessSpawner'> for mal:
[I 2022-01-01 22:28:46.762 JupyterHub log:189] 200 GET /hub/admin (mal@::ffff:172.17.0.1) 92.87ms
[I 2022-01-01 22:28:46.935 JupyterHub log:189] 302 GET /logo -> /hub/logo (@::ffff:172.17.0.1) 7.08ms
[D 2022-01-01 22:28:46.982 JupyterHub log:189] 304 GET /hub/static/js/admin-react.js (@::ffff:172.17.0.1) 12.71ms
[D 2022-01-01 22:28:47.021 JupyterHub log:189] 304 GET /hub/static/css/style.min.css.map (@::ffff:172.17.0.1) 41.23ms
[D 2022-01-01 22:28:47.151 JupyterHub log:189] 200 GET /hub/logo (@::ffff:172.17.0.1) 30.32ms
[D 2022-01-01 22:28:47.206 JupyterHub log:189] 200 GET /hub/static/js/admin.js?v=20220101222832 (@::ffff:172.17.0.1) 1.83ms
[D 2022-01-01 22:28:47.278 JupyterHub scopes:488] Checking access via scope list:groups
[D 2022-01-01 22:28:47.279 JupyterHub scopes:386] Unrestricted access to /hub/api/groups via list:groups
[D 2022-01-01 22:28:47.333 JupyterHub log:189] 304 GET /hub/api/groups?offset=0&limit=50 (mal@::ffff:172.17.0.1) 77.69ms
[D 2022-01-01 22:28:47.347 JupyterHub scopes:488] Checking access via scope list:users
[D 2022-01-01 22:28:47.348 JupyterHub scopes:386] Unrestricted access to /hub/api/users via list:users
[I 2022-01-01 22:28:47.385 JupyterHub log:189] 200 GET /hub/api/users?offset=0&limit=50 (mal@::ffff:172.17.0.1) 118.39ms
[D 2022-01-01 22:28:47.400 JupyterHub log:189] 200 GET /hub/static/js/jhapi.js?v=20220101222832 (@::ffff:172.17.0.1) 9.85ms
[D 2022-01-01 22:28:47.408 JupyterHub log:189] 200 GET /hub/static/js/utils.js?v=20220101222832 (@::ffff:172.17.0.1) 15.91ms
[D 2022-01-01 22:28:47.413 JupyterHub log:189] 200 GET /hub/static/components/moment/moment.js?v=20220101222832 (@::ffff:172.17.0.1) 18.98ms
[D 2022-01-01 22:28:50.014 JupyterHub scopes:488] Checking access via scope servers
[D 2022-01-01 22:28:50.014 JupyterHub scopes:386] Unrestricted access to /hub/api/users/zoe/server via servers
[D 2022-01-01 22:28:50.024 JupyterHub user:347] Creating <class 'jupyterhub.spawner.SimpleLocalProcessSpawner'> for zoe:
[D 2022-01-01 22:28:50.031 JupyterHub base:915] Initiating spawn for zoe
[D 2022-01-01 22:28:50.032 JupyterHub base:919] 0/100 concurrent spawns
[D 2022-01-01 22:28:50.033 JupyterHub base:924] 0 active servers
[D 2022-01-01 22:28:50.056 JupyterHub roles:472] Checking token permissions against requested role server
[I 2022-01-01 22:28:50.072 JupyterHub roles:477] Adding role server to token: <APIToken('aaa0...', user='zoe', client_id='jupyterhub')>
[I 2022-01-01 22:28:50.112 JupyterHub provider:607] Creating oauth client jupyterhub-user-zoe
[D 2022-01-01 22:28:50.155 JupyterHub user:675] Calling Spawner.start for zoe
[I 2022-01-01 22:28:50.164 JupyterHub spawner:1526] Spawning jupyterhub-singleuser --allow-root
[D 2022-01-01 22:28:50.221 JupyterHub spawner:1221] Polling subprocess every 30s
[I 2022-01-01 22:28:52.329 SingleUserLabApp mixins:615] Starting jupyterhub single-user server version 2.0.1
[I 2022-01-01 22:28:52.330 SingleUserLabApp mixins:629] Extending jupyterlab.labhubapp.SingleUserLabApp from jupyterlab 3.2.5
[I 2022-01-01 22:28:52.330 SingleUserLabApp mixins:629] Extending jupyter_server.serverapp.ServerApp from jupyter_server 1.13.1
[I 2022-01-01 22:28:52.390 SingleUserLabApp manager:345] jupyterlab | extension was successfully linked.
[I 2022-01-01 22:28:52.783 SingleUserLabApp manager:345] nbclassic | extension was successfully linked.
[I 2022-01-01 22:28:52.837 SingleUserLabApp manager:367] nbclassic | extension was successfully loaded.
[I 2022-01-01 22:28:52.840 LabApp] JupyterLab extension loaded from /usr/local/lib/python3.8/dist-packages/jupyterlab
[I 2022-01-01 22:28:52.840 LabApp] JupyterLab application directory is /usr/local/share/jupyter/lab
[I 2022-01-01 22:28:52.851 SingleUserLabApp manager:367] jupyterlab | extension was successfully loaded.
[I 2022-01-01 22:28:52.853 SingleUserLabApp mixins:641] Starting jupyterhub-singleuser server version 2.0.1
[I 2022-01-01 22:28:52.867 JupyterHub log:189] 200 GET /hub/api (@127.0.0.1) 1.74ms
[I 2022-01-01 22:28:52.870 SingleUserLabApp serverapp:2582] Serving notebooks from local directory: /tmp/zoe
[I 2022-01-01 22:28:52.870 SingleUserLabApp serverapp:2582] Jupyter Server 1.13.1 is running at:
[I 2022-01-01 22:28:52.871 SingleUserLabApp serverapp:2582] http://127.0.0.1:39161/user/zoe/lab
[I 2022-01-01 22:28:52.871 SingleUserLabApp serverapp:2582]  or http://127.0.0.1:39161/user/zoe/lab
[I 2022-01-01 22:28:52.872 SingleUserLabApp serverapp:2583] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[I 2022-01-01 22:28:52.887 SingleUserLabApp mixins:597] Updating Hub with activity every 300 seconds
[D 2022-01-01 22:28:52.906 JupyterHub base:279] Recording first activity for <APIToken('aaa0...', user='zoe', client_id='jupyterhub')>
[D 2022-01-01 22:28:52.928 JupyterHub base:324] Refreshing auth for zoe
[D 2022-01-01 22:28:52.929 JupyterHub scopes:298] Authenticated with token <APIToken('aaa0...', user='zoe', client_id='jupyterhub')>
[D 2022-01-01 22:28:52.948 JupyterHub scopes:488] Checking access via scope users:activity
[D 2022-01-01 22:28:52.948 JupyterHub scopes:399] Argument-based access to /hub/api/users/zoe/activity via users:activity
[D 2022-01-01 22:28:52.958 JupyterHub users:845] Activity for user zoe: 2022-01-01T22:28:52.813981Z
[D 2022-01-01 22:28:52.960 JupyterHub users:863] Activity on server zoe/: 2022-01-01T22:28:52.813981Z
[I 2022-01-01 22:28:52.996 JupyterHub log:189] 200 POST /hub/api/users/zoe/activity (zoe@127.0.0.1) 98.97ms
[I 2022-01-01 22:28:54.128 SingleUserLabApp log:189] 302 GET /user/zoe/ -> /user/zoe/lab? (@127.0.0.1) 2.04ms
[D 2022-01-01 22:28:54.130 JupyterHub utils:230] Server at http://127.0.0.1:39161/user/zoe/ responded with 302
[D 2022-01-01 22:28:54.130 JupyterHub _version:74] jupyterhub and jupyterhub-singleuser both on version 2.0.1
[I 2022-01-01 22:28:54.131 JupyterHub base:944] User zoe took 4.100 seconds to start
[I 2022-01-01 22:28:54.132 JupyterHub proxy:286] Adding user zoe to proxy /user/zoe/ => http://127.0.0.1:39161
[D 2022-01-01 22:28:54.132 JupyterHub proxy:821] Proxy: Fetching POST http://127.0.0.1:8001/api/routes/user/zoe
22:28:54.137 [ConfigProxy] info: Adding route /user/zoe -> http://127.0.0.1:39161
22:28:54.138 [ConfigProxy] info: Route added /user/zoe -> http://127.0.0.1:39161
22:28:54.141 [ConfigProxy] info: 201 POST /api/routes/user/zoe 
[I 2022-01-01 22:28:54.146 JupyterHub log:189] 201 POST /hub/api/users/zoe/server (mal@::ffff:172.17.0.1) 4135.73ms
[D 2022-01-01 22:28:54.186 JupyterHub scopes:488] Checking access via scope list:users
[D 2022-01-01 22:28:54.187 JupyterHub scopes:386] Unrestricted access to /hub/api/users via list:users
[I 2022-01-01 22:28:54.194 JupyterHub log:189] 200 GET /hub/api/users?offset=0&limit=50 (mal@::ffff:172.17.0.1) 12.21ms
```
</details>

### LINKED ISSUE #3788: Named servers aren't listed on admin page
### Bug description
Reported at https://discourse.jupyter.org/t/named-servers-do-not-show-up-in-admin-console-after-2-0-upgrade/12928

Named servers aren't listed on the hub admin page

#### Expected behaviour
JupyterHub 1.5.0 shows servers `test` and `test/named` for user `test`:
image

#### Actual behaviour
JupyterHub 2.1.1 does not show server `test/named`:
image

### How to reproduce
Start a named server as a non-admin:
image
Log on separately as an admin and go to `/hub/admin`

### Your personal set up
`jupyterhub_config.py`:
```py
c = get_config()
c.JupyterHub.spawner_class = "simple"
c.JupyterHub.authenticator_class = "dummy"
c.Authenticator.admin_users = {'demo'}
c.JupyterHub.allow_named_servers = True
c.JupyterHub.named_server_limit_per_user = 2
```

### PR DESCRIPTION
**Pull request by NarekA**
The current admin console is missing 2 features from previous version:

1. The links to access the users notebooks (closes #3745)
2. Rows cooresponding to named servers (closes #3788)

Screen Shot 2022-02-09 at 11 52 36 AM

### CODE REVIEW

**Comment by NarekA** [comment]
Latest UI, I added a button that links you to the server spawn page so you can re-spawn a server with different parameters.
Screen Shot 2022-02-09 at 1 20 49 PM

**Comment by meeseeksmachine** [comment]
This pull request has been mentioned on **Jupyter Community Forum**. There might be relevant details there:

https://discourse.jupyter.org/t/named-servers-do-not-show-up-in-admin-console-after-2-0-upgrade/12928/3

**Comment by NarekA** [comment]
@naatebarber I see you're the main contributor to this module. Any chance you can take a look at this PR?

**Comment by ykazakov** [comment]
Would it make sense to have a more fine-grain control of the Admin menu based on the new roles/scopes system of Jupyterhub 2.0? That is, to enable the Admin menu also for non-Admin users when they have appropriate roles/scopes like `list:users`, `list:servers` or `access:servers` and show only the respective parts of the Admin menu.

I am asking because I have an impression that admin users are going to be deprecated in favour of more fine-grain permission control. It looks like the key `JupyterHub.admin_access` already does not have any effect in Jupyterhub 2.0 since admin users automatically inherit all scopes.

**Comment by NarekA** [comment]
@ykazakov I agree with your idea, but the scope of this PR is a little more narrow. I want to get feature parity with Jupyterhub 1.0 We recently upgraded our deployment and lost some important management/debugging abilities. Once we get these tools back, I agree that we should expand these features to work with roles and scopes.

**Comment by ykazakov** [comment]
@NarekA I agree that it makes sense to first restore the previous functionality for admin users. I only wondered if you already use the new roles in your patch. How do you now check the permissions to access the server? Using the `access:servers` scope or using the `JupyterHub.admin_access` key?

**Comment by manics** [comment]
@NarekA Thanks for working on this! Do you think it makes sense to remove the duplicate `edit user` buttons so it appears once per user instead of per server?
image

**Comment by NarekA** [comment]
@manics Done! Let me know if you prefer a different layout for this.
Screen Shot 2022-02-11 at 10 46 48 AM

**Comment by NarekA** [comment]
@ykazakov few thing:

1. If we checked scopes and access, wouldn't the same issues apply to the start-server and stop-server buttons? That is why I don't think this PR is the appropriate forum for this conversation.
2. If a user clicks the "Access Server" button, it takes them to the server's URL where the access is checked.
3. From what I understand, admins still have full access to servers, and only admins can access this page at the moment.

**Comment by ykazakov** [comment]
@NarekA I am asking because in Jupyterhub 1.5, by default, admins *cannot* access users notebooks. So the `Access Server` buttons are not even shown in this case:

Screenshot 2022-02-11 at 20 22 46

I think that some check (e.g., for the key `JupyterHub.admin_access`) was performed also in the UI component. Hence is my question, wether there is a similar check now? As you can see, it was still possible for admins to start and stop the user servers even if they cannot access them.

**Comment by NarekA** [comment]
@ykazakov Can you please point me to these checks in the UI components? I don't see any access checks on the admin page frontend.

**Comment by ykazakov** [comment]
I guess this is the place:
https://github.com/jupyterhub/jupyterhub/blob/bf73e6f7b724ad6c976f410839a7162262020e2c/share/jupyterhub/templates/admin.html#L77

**Comment by manics** [comment]
@NarekA Thanks, that update looks good to me!

Unfortunately deciding whether to allow `admin_access` may be a bit complicated, see https://github.com/jupyterhub/jupyterhub/issues/3745#issuecomment-1007396044 and the following discussion.

Summary is we should check whether the user has the `access:server` rather than relying on the `admin_access` property, since it's ultimately the role/scope that determines access. I'm not sure if that covers all cases though, e.g. a non-admin might be allowed to access all servers in a group so they should still see that button.

However, given that this PR already fixes a regression I also think it's fine to keep things simple and just check for `admin_access`, and follow this up with a PR that properly checks the scopes, perhaps as part of the full resolution of https://github.com/jupyterhub/jupyterhub/issues/3745

**Comment by manics** [comment]
Actually the admin page currently _requires_ `admin:servers`:
https://github.com/jupyterhub/jupyterhub/blob/71bbbe4a6772f5c80079c9b123c857c706ac8e89/jupyterhub/handlers/pages.py#L461-L471
which means at the moment if you can access the admin page you can access users servers regardless of `admin_access`. I'm therefore inclined to merge this PR as it is and deal with this separately.

@minrk shall we merge this as is, and deal with whether or not the access link is shown in a separate PR when we've resolved https://github.com/jupyterhub/jupyterhub/issues/3745#issuecomment-1037176686 ?

**Comment by minrk** [comment]
@manics yes! Thanks folks for reviewing and thanks @NarekA for the PR!

Let's tackle using a scope to govern access to the admin page itself in a separate PR, and then the access-server check. There's little harm in having the button there if you don't have access, so the right answer may be to have the button present and just let folks click it - they'll get a 403 if they don't have access.

**Comment by minrk** [comment]
I was wrong! The admin page already requires `admin:users` and `admin:servers`, so you already don't need to be a full admin to use the page. We can think later if there's a reasonable case to be made for a dedicated scope for the UI, but the permissions for now are fine. It's still worth looking through references to the admin_access config since it's meaningless now, and make sure we show links to the admin page for users with the right permissions.

Essentially, there should be no checks anywhere for `if user.admin`.

**Comment by manics** [comment]
I've created a follow-up issue for the admin page https://github.com/jupyterhub/jupyterhub/issues/3797

**Comment by meeseeksmachine** [comment]
This pull request has been mentioned on **Jupyter Community Forum**. There might be relevant details there:

https://discourse.jupyter.org/t/admin-ability-to-access-servers-missing-in-jupyterhub-2-1-1/13160/1

**Comment by NarekA** [comment]
@ykazakov Added a fix for that in my current PR https://github.com/jupyterhub/jupyterhub/pull/3827

**Pull request merged**
