### PR TITLE
make pagination configurable

### LINKED ISSUE #3228: Allow configuring max number of users per page in admin
### Proposed change

Right now, it's impossible to have more than 250 users per-page in the JupyterHub admin page. However, this makes searching for a single user basically impossible - you have to manually paginate through them.

Search functionality is the right way to do this, but until then, I think we should allow using a traitlet to configure how many users can be displayed on a single page.

### Alternative options

Add a user search bar! But that's more work.

### Who would use this feature?

Anyone with more than 250 users on their hub.

### (Optional): Suggest a solution

Add a traitlet to the `JupyterHub` object that gets passed down to the Pagination class, where it can use those numbers instead of the hardcoded limits there.

### PR DESCRIPTION
**Pull request by minrk**
add some unittests for pagination

reorganize pagination a bit to make it easier to configure

still need to do a bit more testing

closes #3228

### CODE REVIEW

**Comment by yuvipanda** [comment]
Awesome, @minrk!!!!

**Comment by consideRatio** [comment]
@minrk I added the enhancement label because it make github-activity automatically categorize the PR for the changelog.

**Comment by yuvipanda** [comment]
Hmm, this seems to not work. 

I've the following in my extra_config:

```yaml
      07-no-pagination: |
        c.Pagination.default_per_page = 10000
        c.Pagination.max_per_page = 10000
```

But pagination still seems to be at 250.

**Comment by minrk** [comment]
Found and fixed it in #3294

**Pull request merged**
