### PR TITLE
Improve debugging when waiting for servers

### PR DESCRIPTION
**Pull request by minrk**
Add debug messages and timers for start and end waiting for servers

and improve logic for awaiting proxy endpoints using concurrency primitives instead of a for-loop

this might have improved debugging of #4557

Sample debug output:

```
[D 2023-09-12 09:27:23.233 JupyterHub utils:251] Waiting 10s for server at heavy:8000
[D 2023-09-12 09:27:23.243 JupyterHub utils:98] Server at heavy:8000 not ready: [Errno 61] Connection refused
[D 2023-09-12 09:27:23.243 JupyterHub utils:251] Waiting 10s for server at 127.0.0.1:8001
[D 2023-09-12 09:27:23.243 JupyterHub utils:98] Server at 127.0.0.1:8001 not ready: [Errno 61] Connection refused
09:27:23.327 [ConfigProxy] info: Proxying http://*:8000 to (no default)
09:27:23.329 [ConfigProxy] info: Proxy API at http://127.0.0.1:8001/api/routes
[D 2023-09-12 09:27:23.384 JupyterHub utils:261] Server at 127.0.0.1:8001 responded in 0.14s
[D 2023-09-12 09:27:23.416 JupyterHub utils:261] Server at heavy:8000 responded in 0.18s
[D 2023-09-12 09:27:23.416 JupyterHub proxy:799] Proxy started and appears to be up
```

### CODE REVIEW

**Review by consideRatio — COMMENTED** [review]
I think the logic is correct, but I had comments about readability

- The function no longer has a `_` prefix, shouldn't it have that still?
- name and docstring didn't help me understand what the function did so well, and with the function not being prefixed with `_` I think we should make sure to get this tightly defined.
  - based on name/docstring, I was surprised to see the externally defined servers_ready awaited
- A variable name `process_ended` doesn't meet my expectations, currently understanding it to represents that the watching of the proxy initialization had ended or similar.
- The comment `# whichever comes first` wasn't representing what `wait_for -> gather (A, b)` does, but its kind of true anyhow because to await A is to await `a` or `b`.

I'm not sure if this would work out correctly, but with regards to the "wait for first", maybe we can use:
- one awaitable for early termination of proxy process (sleeps 0.5 second between poll)
- one awaitable for servers ready
- use of `asyncio.wait` with a `return_when` argument set to `FIRST_COMPLETED`, more info in reference https://docs.python.org/3/library/asyncio-task.html#waiting-primitives
  - manually cancelling waited futures if returned or timeout...
  
Hmmm... I'm not sure, we can merge this as it if but I think this was quite tricky to understand and therefore maintain longterm as it is now.

**Comment by minrk** [comment]
Thanks for the feedback! I've pushed an updated implementation that uses the lower-level `wait` instead of relying on `wait_for`, I think it should be more clear and explicit, if more complex in terms of cases to handle explicitly.

> The function no longer has a _ prefix, shouldn't it have that still?

I don't think it makes sense to use private naming prefixes for functions defined in closures. Nobody can ever call this function so it's not an API. If Python had anonymous blocks, that's what I think would be most appropriate here.

> A variable name process_ended doesn't meet my expectations, currently understanding it to represents that the watching of the proxy initialization had ended or similar.

It is a Future that resolves only when the process has ended, but cancels itself when it's no longer needed. That cancelling itself is weird, I admit! I'll look at avoiding it.

> The comment `# whichever comes first` wasn't representing what wait_for -> gather (A, b) does, but its kind of true anyhow because to await A is to await a or b.

I think this accurately describes what happens here, but here's a more detailed description of the possible situations:

1. servers wait_up complete with success (wait_for returns immediately)
2. process exits before both wait_ups finish (wait_for raises RuntimeError immediately)
3. _either_ wait_up raises an error (wait_for raises error immediately)
4. one or both wait_up doesn't finish within the deadline (wait_for raises TimeoutError)

and the use of `wait_for` ensures cancellation of whichever task doesn't finish first.

I can rewrite it to use `wait` instead of `wait_for`, but then we are reimplementing all the logic of wait_for (cancel pending tasks, raise TimeoutError, etc.). Maybe that would be clearer and more explicit, though.

**Comment by consideRatio** [comment]
Yikes this cascaded to significant additional work for you, I'm sorry! Thank you for the clear followups and effort into this.

> I don't think it makes sense to use private naming prefixes for functions defined in closures. Nobody can ever call this function so it's not an API. If Python had anonymous blocks, that's what I think would be most appropriate here.

Oh I didn't realize this was just defined inside another function, makes sense!

> I can rewrite it to use wait instead of wait_for, but then we are reimplementing all the logic of wait_for (cancel pending tasks, raise TimeoutError, etc.). Maybe that would be clearer and more explicit, though.

Ah yes this certainly added complexity as well.

**Comment by minrk** [comment]
@meeseeksdev please backport to 4.x

**Pull request merged**
