### PR TITLE
WIP: Redirect if source user's server is running

### PR DESCRIPTION
**Pull request by bobbychopra**
Redirects notebook URL to user's server if source user's server is running

### CODE REVIEW

**Comment by minrk** [comment]
I don't believe that this redirect should be performed. At most, the desired URL should be displayed as a suggested "Did you mean..." link, with an explanation about the `user-redirect` url. Too many automatic redirects guessing at what users wanted has been a major problem for JupyterHub.

Would you like to take a stab at implementing that?

**Comment by msuperina** [comment]
@minrk to give you more context https://github.com/jupyterhub/jupyterhub/issues/2464 was a question in preparation of this PR. 
The motivation behid this question is that we have users who want to share notebooks by copy pasting the url from the browser. 
We have already implemented extensions to generate the /user-redirect link with a single click but those users do not find those extensions obvious enough.

**Comment by minrk** [comment]
What about my proposal above, including the link in the error page? That would make it just one extra click away, but I would like to stick strongly to the fact that this is a result of an error made by the user, and should be treated as such.

**Comment by bobbychopra** [comment]
The suggestion _"Did you mean..." link with an explanation about the user-redirect url_ is an option. It isn't something that we are keen to implement as we feel that user: bob should have accesses the notebook using user: alice url's link if alice's server is stopped or is running

The current behavior is confusing for our users because:
- user: bob **can** accesses the notebook using user: alice url's link if alice's server is stopped, but 
- user: bob **cannot** accesses the notebook and receives a 403 HTTP Error using user: alice url's link if alice's server is running

We get tons of complaints from user: bob why the user:alice's url suddenly stopped working.

**Comment by minrk** [comment]
We can get to consistent behavior with the above proposal, because we can then stop redirecting users from a page they cannot access to a guessed but not necessarily correct URL on their own server. We can fully consistently show the error page with a "Did you mean..." link, which users only click if that's where they wanted to go.

Given that the current redirect has proved to be a huge problem, adding it more places is not something I'm comfortable accepting. We need to move in the opposite direction, but we can still achieve the goal of getting users where they intend to go with an appropriate link on the error page.

**Comment by bobbychopra** [comment]
Your last proposal to show the "Did you mean ..." link would make the behavior pretty consistent. 

To confirm:
If user: bob accesses the notebook using user: alice url's link if alice's server is stopped, **we will show HTTP 403** and present a "Did you mean ..." link
If user: bob accesses the notebook using user: alice url's link, if alice's server is stopped, we show HTTP 403 and can present a "Did you mean ..." link

Please let me know if you have a different approach.

**Comment by minrk** [comment]
@bobbychopra yes, that's exactly right. Same 403 error in both cases, same "Did you mean..." link to the user's own server.

**Comment by minrk** [comment]
oh, and the "Did you mean" link should probably be to `/user-redirect/...`, not `/user/bob/...`. That way, it shows users the *correct* shareable link, not just the final destination.

**Comment by consideRatio** [comment]
@bobbychopra thank you for suggesting an improvement to this project!

I agree with Min that it would be more reliable in the long term to have a change that doesn't automatically redirect a user, but instead have a error with a suggestion added to it. My dream outcome would be to have a 403 error indicating that JupyterHub has spawned a server for user X and you tried to access it, but you could start / go to your own server if that is desired instead.

**Pull request closed without merging**
