### PR TITLE
unpin pytest-asyncio

### PR DESCRIPTION
**Pull request by minrk**
need to wait for module-level async fixtures to be fixed upstream before we can proceed much farther: https://github.com/pytest-dev/pytest-asyncio/issues/718

### CODE REVIEW

**Comment by manics** [comment]
https://github.com/pytest-dev/pytest-asyncio/issues/718#issuecomment-2227092576 was closed, and now refers to:
- https://github.com/pytest-dev/pytest-asyncio/issues/706
- https://github.com/pytest-dev/pytest-asyncio/issues/868
- https://github.com/pytest-dev/pytest-asyncio/issues/829

**Comment by seifertm** [comment]
I just tried to upgrade to pytest-asyncio-0.24.0a0, but I ran into issues with the `io_loop` fixture. It looks like the underlying issue is https://github.com/pytest-dev/pytest-asyncio/issues/668.
Let's see if we can fix this as part of the v0.24 release.

**Comment by minrk** [comment]
@seifertm thanks! I think the new `asyncio_default_fixture_loop_scope = module` config is actually going to be just about all we need for this project, once it's fully working.

I removed our `event_loop` fixture, replacing it with:

```python
asyncio_default_fixture_loop_scope = module
```

and

```python
pytestmark = pytest.mark.asyncio(loop_scope="module")
```

and I can run each test module on its own, but run into https://github.com/pytest-dev/pytest-asyncio/issues/862 when trying to run more. Added more [detail and a reproducer](https://github.com/pytest-dev/pytest-asyncio/pull/906#issuecomment-2272904209) to https://github.com/pytest-dev/pytest-asyncio/pull/906 which so far appears to be a _partial_ fix.

**Comment by minrk** [comment]
@seifertm I've got the tests working with 0.24 now, thank you! The main thing was needing to restore the `modifyitems` hook, as the scope of the overridden `event_loop` fixture no longer sets the loop used in tests.

At the moment, I've gone with a version test:

- if >= 0.24: set scope with modifyitems, don't define `event_loop`
- if < 0.24: define `event_loop` with module scope

**Comment by minrk** [comment]
tests on CI are failing, but I expect them to pass when there is a prerelease of pytest-asyncio with https://github.com/pytest-dev/pytest-asyncio/pull/906. They pass locally for me with that PR checked out.

**Comment by seifertm** [comment]
The pytest-asyncio v0.24.0a1 pre-release is now available.

**Comment by minrk** [comment]
@seifertm thanks! All tests are passing with 0.24.0a1 (most tests) and 0.17.2 (check lower-bounds run).

**Pull request merged**
