### PR TITLE
Restructured Community communication channels file

### PR DESCRIPTION
**Pull request by alwasega**
I have restructured the Community file to make it more readable.

### CODE REVIEW

**Comment by minrk** [comment]
There are already two earlier proposals to update this file (#4081 and #4065). Please select a file that does not already have outstanding changes.

**Comment by alwasega** [comment]
Hi @minrk, 
Do you mean we can only work on files with no outstanding PRs? 
If that is the case, @sgibson91 please update the contribution instructions provided, as more of us are likely to be working on files with pending changes. The instructions only mention that we should avoid working on documents on the `Work in Progress` column but not that we should move our names to the `Done` column only if a PR has been merged. 

Thanks.

**Comment by minrk** [comment]
@alwasega You are certainly _allowed_ to, but we cannot review or merge more than one PR to a file at a time, so if you open a PR to a file with outstanding changes, we have to wait to review it until after the earlier PRs have been merged or closed. That's what the spreadsheet is for - to try to minimize these conflicts by preventing multiple people working on the same file. The earlier PRs have been merged in this case, so we can review this PR once the conflicts have been resolved.

**Comment by alwasega** [comment]
Thank you @minrk , 
Would it be easier on your end if I closed this PR and opened another one with my updates but based on the newer file version? 
Please let me know. 
Thanks.

**Comment by minrk** [comment]
@alwasega the other PRs have been merged. It's up to you whether it's easier to open a new PR or resolve conflicts / rebase this PR. Ultimately, there's no difference whether you push the updated changes to your `community` branch or a new one. If you choose to open a new one, please close this one with a link to it.

**Comment by alwasega** [comment]
Hi @minrk. Please check whether commit #74b0ebefe974a66aac67cebea41df0262bf60888 above is okay. 
Thank you.

**Comment by minrk** [comment]
Terrific, thank you!

**Comment by alwasega** [comment]
> Terrific, thank you!

Thank you too!

**Pull request merged**
