### PR TITLE
Improve query performance with eager loading

### PR DESCRIPTION
**Pull request by minrk**
Reduces the number of queries by using eager loading as appropriate.

Using an ORM lets us hide queries behind property access (convenient), but this can get unintentionally expensive when we are accessing properties as if they are local in very large queries (#4485).

Switches ORM from using the legacy 'backref' to the more explicit 'back_populates'. This has no change on the database or behavior, but makes both directions of each relationship explicit, rather than defining it on only one side. This helps us specify the chosen lazy-loading options in the right places.

More info on [loading relationships in sqlalchemy](https://docs.sqlalchemy.org/en/20/tutorial/orm_related_objects.html#tutorial-orm-loader-strategies).

In general, the choices are:

- eager loading defined on the relationship itself, so that it's fetched by default when we fetch the object. This makes sense when the relationship is almost certainly used when the object is used (e.g. Spawner.server, APIToken.user).
  Currently this applies to:
  - User.groups, User.roles (used for permissions resolution)
  - Group.roles
  - Spawner.server, user
  - Service.server, roles
  - APIToken.user, service, oauth_client
  - OAuthCode.user, client
  - OAuthClient.spawner, service
- eager loading defined on a particular query via `query.options`. This is useful when a specific request is likely to look at a lot of the relationships (e.g. `GET /api/users` should resolve group/spawner/server relationships)
  - GET /api/users: adds User.spawners
  - May apply to getting user from APIToken, if we don't always get groups/roles from user above
- _raise_ loading to essentially assert that there's no lazy loading going on. I'm using this now for debugging, and hope to enable it for tests in particular, but don't think we should use it in production, since it turns inefficiencies into errors.

In general, this _increases_ the cost of the initial queries, at the expense of reducing the follow-up queries if/when we know they are going to happen, so we need to be careful to not get _too_ eager, loading things we aren't going to use (e.g. I need to make sure we aren't making GET /api/groups too expensive by fetching lots of relationships we aren't going to use about users)

I need to run some profiling to validate that this is actually improving things, not making it worse.

TODO:

- [x] reduce queries in startup by only updating things that need changing (#4496)
- [x] reduce queries in GET /api/users
- [x] reduce queries in cheecking request permissions
- [x] check GET /api/groups for inefficiencies
- [x] profile improvements to make sure this actually helps
- [x] remove raiseload/debugging

I may pull the startup performance out to its own PR, since it turns out to be fairly independent of the other changes.

### CODE REVIEW

**Comment by minrk** [comment]
working on the profiling, but this currently has the GET /users for 5k users (paginated requests) down from 14,000 db operations to ~600, a reduction of 95%, and reducing from 14 seconds to 0.6, assuming 1ms latency for each db operation (local sqlite is much quicker than that, but a remote db may not be).

**Comment by minrk** [comment]
Everything works, except I need to tweak something for sqlalchemy 1.4 compatibility.

**Comment by minrk** [comment]
This could perhaps use some refinement, but I think it's a dramatic improvement. db queries are down to 5 per GET /users (regardless of the number of users), from ~5 _per user_ per GET /users (down from 20160 queries to GET 5000 inactive users in 50 pages to 257 for the same requests and same results).

Much further loading optimizations are hard to do while we have a shared db session. This can be further improved as we move to per-request db sessions.

**Comment by ryanlovett** [comment]
Hi @minrk , is this going to be added to 4.x branch for a 4.x release?

**Pull request merged**
