### PR TITLE
clarify CHP downsides in proxy doc

### PR DESCRIPTION
**Pull request by lumenCodes**

### CODE REVIEW

**Comment by lumenCodes** [comment]
I can see that a lot of commits were added here and this is not what I intend to do. I am looking for how to remove these commits from this branch If I do not find a solution to it then I might have delete the branch and start afresh.

**Comment by minrk** [comment]
If you can't figure it out, opening a new PR from a different branch is fine. The command you are looking for is `git rebase` which will let you remove the commits you didn't mean to add, then you can force push to your `proxy` branch to update it.

**Comment by lumenCodes** [comment]
Thanks @minrk I just rebased the branch now.

**Comment by minrk** [comment]
great, thanks!

**Pull request merged**
