### PR TITLE
changelog for 1.2.0b1

### PR DESCRIPTION
**Pull request by consideRatio**
This is a preliminary changelog for an upcoming JupyterHub 1.2.0b1 release.

I used @choldgraf's excellent github-activity tool to first generate a markdown file with all kinds of PRs made since 1.1.0. Then I opened all the PRs and added a bug/enhancement/maintenance/documentation label to every PR to the best of my ability, and then I ran the tool again, which now categorized the PRs for me.

If we want to update this changelog, we can in other words just re-run the tool and label the PRs that have arrived since.

```shell
pip install -U git+https://github.com/executablebooks/github-activity
github-activity jupyterhub/jupyterhub --since 3663d7c8 --output changelog.md
```

## Related
- KubeSpawner 0.14.0 changelog PR - https://github.com/jupyterhub/kubespawner/pull/443
- JupyterHub 1.2.0b1 changelog PR - https://github.com/jupyterhub/jupyterhub/pull/3192
- Z2JH 0.10.0-beta.1 changelog PR - https://github.com/jupyterhub/zero-to-jupyterhub-k8s/pull/1795

### CODE REVIEW

**Comment by consideRatio** [comment]
@minrk could you activate read the docs new feature allowing for PR builds?

## Convenience links
Link to check "Build pull requests for this project": https://readthedocs.org/dashboard/jupyterhub/advanced/
RTD documentation about the feature: https://docs.readthedocs.io/en/latest/guides/autobuild-docs-for-pull-requests.html

**Comment by choldgraf** [comment]
One quick thought - I think it'd be helpful if in addition to these lists of PRs, we also included a few summary takeaways with explanations about the major things users should be aware of. See the v0.8 changelog for some examples:

https://jupyterbook.org/reference/_changelog.html#v0-8-0-2020-09-01

In that case we actually wrote a short summary for *each* PR that was merged, but that's probably a bit extreme.

**Comment by minrk** [comment]
I checked the box, might need another push

@choldgraf I completely agree that a human-selected collection of highlights is important for every release, since it is very hard to tell which, if any, of a large number PRs are important for upgraders to be aware of.

I don't think I have time to put into this before next Tuesday, but I can have a stab after that if nobody else does.

I think if @consideRatio wants to start the beta cycle with the purely auto changelog, that's okay with me, but we should have this before a full release.

I think this is a "lots of little things" release without many big warnings/caveats/selling points for upgrading, which can make writing the highlights/summary a little tricky.

**Comment by minrk** [comment]
I added some highlights. Shall we merge and cut the beta?

**Comment by consideRatio** [comment]
@minrk I updated the changelog with the latest merged PRs and such, I'll merge this now! Let's cut the beta!

**Pull request merged**
