### PR TITLE
transferred docs to the FAQ folder

### PR DESCRIPTION
**Pull request by alwasega**
I have transferred the files marked for the `FAQ` section of the documentation.

### CODE REVIEW

**Comment by alwasega** [comment]
Hi @sgibson91, @minrk,  
Please check this draft PR.

**Comment by minrk** [comment]
LGTM!

@sgibson91 we should probably be adding rediraffe targets for these renames to avoid breaking all the links, right?

**Comment by alwasega** [comment]
Thank you, @minrk.

**Comment by sgibson91** [comment]
@minrk Probably a good idea, but I haven't used rediraffe myself. @GeorgianaElena perhaps you could come to mine and Allan's next meeting and demonstrate how to add redirects?

**Comment by sgibson91** [comment]
But I also think that swapping the links from filepaths to myst references is a good thing anyway, as they'll be robust against future moves.

**Comment by minrk** [comment]
Yes, for rediraffe I'm thinking mainly of public links to our docs website, not the internal references. We should probably be doing myst targets for _internal_ links everywhere (many of our markdown docs predate myst and file refs were all we had).

**Comment by sgibson91** [comment]
I'll merge this for now, to not block Allan, and we can come back around to add redirects for the files moved in the previous PRs once we know how

**Comment by alwasega** [comment]
Thanks @sgibson91 and @minrk.

**Comment by GeorgianaElena** [comment]
> @GeorgianaElena perhaps you could come to mine and Allan's next meeting and demonstrate how to add redirects?

@sgibson91, absolutely! In the meantime, I will also share some code references of redirects being added in the past in case they make sense and we don't block this on the meeting?

- this is @consideRatio specifying the new location of the doc files that were moved and renamed in the `team-compass` repo, for rediraffe to pick up https://github.com/2i2c-org/team-compass/pull/596
- this is me doing the same in the `oauthenticator` repo  https://github.com/jupyterhub/oauthenticator/commit/28dfe7a2a857913f7f5ffa761418125f85dbd707. 

Also, this is rediraffe's documentation https://sphinxext-rediraffe.readthedocs.io/en/latest/ for additional info. I notice an [Auto Redirect builder](https://sphinxext-rediraffe.readthedocs.io/en/latest/#auto-redirect-builder) is available, but I haven't used it myself and instead added the new location of the files as redirects manually.

**Pull request merged**
