### PR TITLE
MNT: Add hub host and prefix to template vars in prep for JLab extension

### PR DESCRIPTION
**Pull request by danielballan**
See https://github.com/jupyter/jupyterlab/pull/1071

A PR with the actual extension that uses this change is forthcoming. It would be great to get this (and maybe also the extension itself, if it's ready) into the next tagged release.

### CODE REVIEW

**Comment by minrk** [comment]
Is the Hub private URL really desirable here? That's a private host that's accessible to the notebook server, but generally not accessible to the *client* who is getting the javascript context.

**Comment by minrk** [comment]
Ignore me, I was thinking of api_url. hub_host is exactly right here.

**Comment by minrk** [comment]
I'll add some comments so that it's clearer what everything is, since I'm clearly forgetting.

**Comment by danielballan** [comment]
No worries, thanks.

**Pull request merged**
