### PR TITLE
Update issue templates

### PR DESCRIPTION
**Pull request by GeorgianaElena**
This PR changes the issue templates into: 
templates

And aims to redirect people to Discourse for support questions and configuration assistance as discussed in https://github.com/jupyterhub/jupyterhub/issues/2996.

### CODE REVIEW

**Comment by willingc** [comment]
@manics Do you want to review?

**Comment by consideRatio** [comment]
Wieeee excellent work on this everyone involved! :heart: :tada: LGTM!

**Comment by consideRatio** [comment]
Things I appreciated:
- The bug/feature templates were short and concise
- The feature request template asked questions in a way I think can help nudge the person to help implementing it.

**Comment by GeorgianaElena** [comment]
I'm very happy you liked it @consideRatio. But this not at all my merit as these templates are taken from repo2docker and slightly adapted to the JH repo. @betatim and @KirstieJane did all this great work :heart:

**Comment by manics** [comment]
I've opened a follow-up issue to discuss how to roll this out to other repos: https://github.com/jupyterhub/team-compass/issues/271

**Pull request merged**
