### PR TITLE
Rollback database sessions on SQLAlchemy errors

### LINKED ISSUE #1626: Jupyterhub is not resilient with external MySQL database
We are using Jupyterhub with an external mariadb(open source fork of mysql) database. In the event of a temporary network failure, Jupyterhub gets stuck and do not recover.

**How to reproduce the issue on mac**

1. Install Mariadb locally
`brew install mariadb`
2. Remove from launchctl for ease of stop and start
`launchctl unload -w ~/Library/LaunchAgents/homebrew.mxcl.mariadb.plist`
3. Start mariadb
`brew services start mariadb`
4. Create a database named jh_test
5. Create a user test/test in mac.
6. Run jupyter hub locally with following config file.
```
c = get_config()
c.Authenticator.whitelist = {'test'}
c.Authenticator.admin_users = {'test'}
c.JupyterHub.db_url = 'mysql+mysqlconnector://{}:{}@{}/{}{}'.format("root","","localhost","jh_test","")
```
7. Login using test/test and start jupyter server.
8. Stop mysql
`brew services stop mariadb`
9. Go to browser and click on Control Panel button. You'll get following exception:
```
[E 2018-01-19 04:14:19.920 JupyterHub web:1518] Exception in exception handler
    Traceback (most recent call last):
      File "/Users/bhatt/anaconda3/lib/python3.6/site-packages/tornado/web.py", line 1516, in _execute
        self._handle_request_exception(e)
      File "/Users/bhatt/anaconda3/lib/python3.6/site-packages/tornado/web.py", line 1570, in _handle_request_exception
        self.send_error(500, exc_info=sys.exc_info())
      File "/Users/bhatt/anaconda3/lib/python3.6/site-packages/tornado/web.py", line 1040, in send_error
        self.finish()
      File "/Users/bhatt/anaconda3/lib/python3.6/site-packages/jupyterhub/handlers/base.py", line 105, in finish
        super().finish(*args, **kwargs)
      File "/Users/bhatt/anaconda3/lib/python3.6/site-packages/tornado/web.py", line 993, in finish
        self._log()
      File "/Users/bhatt/anaconda3/lib/python3.6/site-packages/tornado/web.py", line 1540, in _log
        self.application.log_request(self)
      File "/Users/bhatt/anaconda3/lib/python3.6/site-packages/tornado/web.py", line 2053, in log_request
        self.settings["log_function"](handler)
      File "/Users/bhatt/anaconda3/lib/python3.6/site-packages/jupyterhub/log.py", line 90, in log_request
        user = handler.get_current_user()
      File "/Users/bhatt/anaconda3/lib/python3.6/site-packages/jupyterhub/handlers/base.py", line 229, in get_current_user
        return self.get_current_user_cookie()
      File "/Users/bhatt/anaconda3/lib/python3.6/site-packages/jupyterhub/handlers/base.py", line 222, in get_current_user_cookie
        return self._user_for_cookie(self.hub.cookie_name)
      File "/Users/bhatt/anaconda3/lib/python3.6/site-packages/jupyterhub/handlers/base.py", line 206, in _user_for_cookie
        u = self.db.query(orm.User).filter(orm.User.cookie_id==cookie_id).first()
      File "/Users/bhatt/anaconda3/lib/python3.6/site-packages/sqlalchemy/orm/query.py", line 2755, in first
        ret = list(self[0:1])
      File "/Users/bhatt/anaconda3/lib/python3.6/site-packages/sqlalchemy/orm/query.py", line 2547, in __getitem__
        return list(res)
      File "/Users/bhatt/anaconda3/lib/python3.6/site-packages/sqlalchemy/orm/query.py", line 2855, in __iter__
        return self._execute_and_instances(context)
      File "/Users/bhatt/anaconda3/lib/python3.6/site-packages/sqlalchemy/orm/query.py", line 2878, in _execute_and_instances
        result = conn.execute(querycontext.statement, self._params)
      File "/Users/bhatt/anaconda3/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 945, in execute
        return meth(self, multiparams, params)
      File "/Users/bhatt/anaconda3/lib/python3.6/site-packages/sqlalchemy/sql/elements.py", line 263, in _execute_on_connection
        return connection._execute_clauseelement(self, multiparams, params)
      File "/Users/bhatt/anaconda3/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1053, in _execute_clauseelement
        compiled_sql, distilled_params
      File "/Users/bhatt/anaconda3/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1121, in _execute_context
        None, None)
      File "/Users/bhatt/anaconda3/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1402, in _handle_dbapi_exception
        exc_info
      File "/Users/bhatt/anaconda3/lib/python3.6/site-packages/sqlalchemy/util/compat.py", line 203, in raise_from_cause
        reraise(type(exception), exception, tb=exc_tb, cause=cause)
      File "/Users/bhatt/anaconda3/lib/python3.6/site-packages/sqlalchemy/util/compat.py", line 186, in reraise
        raise value.with_traceback(tb)
      File "/Users/bhatt/anaconda3/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1114, in _execute_context
        conn = self._revalidate_connection()
      File "/Users/bhatt/anaconda3/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 424, in _revalidate_connection
        "Can't reconnect until invalid "
    sqlalchemy.exc.StatementError: (sqlalchemy.exc.InvalidRequestError) Can't reconnect until invalid transaction is rolled back [SQL: 'SELECT users.id AS users_id, users.name AS users_name, users.`admin` AS users_admin, users.last_activity AS users_last_activity, users.cookie_id AS users_cookie_id, users.state AS users_state, users.encrypted_auth_state AS users_encrypted_auth_state \nFROM users \nWHERE users.cookie_id = %(cookie_id_1)s \n LIMIT %(param_1)s'] [parameters: [{}]]
```
10. Start mariadb again
`brew services start mariadb`
11. Refresh Jupyterhub page.
**What you expected to happen**
Jupyterhub should reconnect with DB and work normally as network interruptions are common scenarios. In above case DB was shutdown to mimic network interruption. Results are same with a remote DB and actual n/w interruption.
**What actually happens**
Jupyter hub keeps giving above exception and we need to restart hub for bringing it back to normal state.
**Share what version of JupyterHub you are using**
0.8.1

### PR DESCRIPTION
**Pull request by minrk**
Unfortunately, I don't know how to write a synthetic test for this. But I was able to follow the instructions in #1626 and reproduce the error and it is fixed by this PR.

closes #1626

### CODE REVIEW

**Comment by mak-aravind** [comment]
@minrk  Thank you very much for the fixes. I got a chance to test your changes from the implementation we are doing for jupyter. Actually your fix helps the hub from looping and reporting below error:

_sqlalchemy.exc.StatementError: (sqlalchemy.exc.InvalidRequestError) Can't reconnect until invalid transaction is rolled back [SQL: 'SELECT users.id AS users_id, users.name AS users_name, users.admin AS users_admin, users.last_activity AS users_last_activity, users.cookie_id AS users_cookie_id, users.state AS users_state, users.encrypted_auth_state AS users_encrypted_auth_state \nFROM users \nWHERE users.name = %(name_1)s \n LIMIT %(param_1)s'] [parameters: [{}]]_

When we open a browser and access the jupyterhub it is immediatly shows up a login page. For Dev I am using https://github.com/yuvipanda/jupyterhub-dummy-authenticator. But thereafter when I login with a user name its throwing 500 : Internal Server Error. With below logs from hub and the url used is 

http://192.168.39.45:31212/hub/login?next=

When I relaunch the jupyter from another browser window or tab the login happens without 500 : Internal Server Error. Or otherwise clicking the top left corner jupyterhub dashboard icon also brings back to login page and when I login from there it goes through without error. 
I hope we should show proper customised error message for this system error. 

Please let me know your thoughts

`[E 2018-05-16 19:51:24.218 JupyterHub web:1621] Uncaught exception POST /hub/login?next= (172.17.0.1)
    HTTPServerRequest(protocol='http', host='192.168.39.45:31212', method='POST', uri='/hub/login?next=', version='HTTP/1.1', remote_ip='172.17.0.1')
    Traceback (most recent call last):
      File "/usr/local/lib/python3.6/dist-packages/tornado/web.py", line 1543, in _execute
        result = yield result
      File "/usr/local/lib/python3.6/dist-packages/jupyterhub/handlers/login.py", line 81, in post
        user = await self.login_user(data)
      File "/usr/local/lib/python3.6/dist-packages/jupyterhub/handlers/base.py", line 469, in login_user
        user = self.user_from_username(username)
      File "/usr/local/lib/python3.6/dist-packages/jupyterhub/handlers/base.py", line 290, in user_from_username
        user = self.find_user(username)
      File "/usr/local/lib/python3.6/dist-packages/jupyterhub/handlers/base.py", line 285, in find_user
        orm_user = orm.User.find(db=self.db, name=name)
      File "/usr/local/lib/python3.6/dist-packages/jupyterhub/orm.py", line 194, in find
        return db.query(cls).filter(cls.name == name).first()
      File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/orm/query.py", line 2825, in first
        ret = list(self[0:1])
      File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/orm/query.py", line 2617, in __getitem__
        return list(res)
      File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/orm/query.py", line 2925, in __iter__
        return self._execute_and_instances(context)
      File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/orm/query.py", line 2948, in _execute_and_instances
        result = conn.execute(querycontext.statement, self._params)
      File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/engine/base.py", line 948, in execute
        return meth(self, multiparams, params)
      File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/sql/elements.py", line 269, in _execute_on_connection
        return connection._execute_clauseelement(self, multiparams, params)
      File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/engine/base.py", line 1060, in _execute_clauseelement
        compiled_sql, distilled_params
      File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/engine/base.py", line 1132, in _execute_context
        None, None)
      File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/engine/base.py", line 1413, in _handle_dbapi_exception
        exc_info
      File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/util/compat.py", line 203, in raise_from_cause
        reraise(type(exception), exception, tb=exc_tb, cause=cause)
      File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/util/compat.py", line 186, in reraise
        raise value.with_traceback(tb)
      File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/engine/base.py", line 1125, in _execute_context
        conn = self._revalidate_connection()
      File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/engine/base.py", line 427, in _revalidate_connection
        "Can't reconnect until invalid "
    sqlalchemy.exc.StatementError: (sqlalchemy.exc.InvalidRequestError) Can't reconnect until invalid transaction is rolled back [SQL: 'SELECT users.id AS users_id, users.name AS users_name, users.admin AS users_admin, users.created AS users_created, users.last_activity AS users_last_activity, users.cookie_id AS users_cookie_id, users.state AS users_state, users.encrypted_auth_state AS users_encrypted_auth_state \nFROM users \nWHERE users.name = %(name_1)s \n LIMIT %(param_1)s'] [parameters: [{}]]
    
[W 2018-05-16 19:51:24.219 JupyterHub base:806] Rolling back session due to database error (sqlalchemy.exc.InvalidRequestError) Can't reconnect until invalid transaction is rolled back [SQL: 'SELECT users.id AS users_id, users.name AS users_name, users.admin AS users_admin, users.created AS users_created, users.last_activity AS users_last_activity, users.cookie_id AS users_cookie_id, users.state AS users_state, users.encrypted_auth_state AS users_encrypted_auth_state \nFROM users \nWHERE users.name = %(name_1)s \n LIMIT %(param_1)s'] [parameters: [{}]]
[E 2018-05-16 19:51:24.222 JupyterHub log:150] {
      "Cookie": "_xsrf=2|1bd0a1a1|12ed2a834fe070b00759531eeda7f0f9|1526446758",
      "Accept-Language": "en-US,en;q=0.9",
      "Accept-Encoding": "gzip, deflate",
      "Referer": "http://192.168.39.45:31212/hub/login",
      "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8",
      "User-Agent": "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/66.0.3359.139 Safari/537.36",
      "Content-Type": "application/x-www-form-urlencoded",
      "Upgrade-Insecure-Requests": "1",
      "Origin": "http://192.168.39.45:31212",
      "Cache-Control": "max-age=0",
      "Content-Length": "22",
      "X-Scheme": "http",
      "X-Original-Uri": "/hub/login?next=",
      "X-Forwarded-Proto": "http,http",
      "X-Forwarded-Port": "80,31212",
      "X-Forwarded-Host": "192.168.39.45:31212",
      "X-Forwarded-For": "172.17.0.1,172.17.0.5",
      "X-Real-Ip": "172.17.0.1",
      "Connection": "close",
      "Host": "192.168.39.45:31212"
    }
[E 2018-05-16 19:51:24.223 JupyterHub log:158] 500 POST /hub/login?next= (@172.17.0.1) 6.79ms
[I 2018-05-16 19:52:20.019 JupyterHub proxy:299] Checking routes
[I 2018-05-16 19:53:19.953 JupyterHub proxy:299] Checking routes
[I 2018-05-16 19:54:19.956 JupyterHub proxy:299] Checking routes
[I 2018-05-16 19:55:19.953 JupyterHub proxy:299] Checking routes
[I 2018-05-16 19:56:19.982 JupyterHub proxy:299] Checking routes
[I 2018-05-16 19:57:19.957 JupyterHub proxy:299] Checking routes
[I 2018-05-16 19:58:19.956 JupyterHub proxy:299] Checking routes
[I 2018-05-16 19:59:19.958 JupyterHub proxy:299] Checking routes
`

**Comment by minrk** [comment]
@mak-aravind thanks for testing. I pushed another change from the sqlalchemy docs that ought to improve things (when connections are lost, it shouldn't fail, it will reconnect *first*).

So we now have two changes here:

1. hub resiliency to db errors (missing rollback call on errors)
2. check connection validity before using it (avoids db errors altogether if reconnect happens not during a specific transaction).

**Comment by minrk** [comment]
Merging this for 0.9b3. Please continue testing and reporting issues! Thanks for your help.

**Comment by chicocvenancio** [comment]
We have a beta instance running jupyterhub 0.9b3 and it survived a db reboot today, while the one running 0.8.1 didn't!

**Comment by serlina** [comment]
@ mak-aravind, as you said several days ago
""""
@minrk With this fix # 1894, After bringing down postgres and resuming its service there are some observations I collated below :

when I open a browser and access the jupyterhub it immediately shows up a login page. For Dev I am using https://github.com/yuvipanda/jupyterhub-dummy-authenticator. When I login with a username its throwing 500: Internal Server Error. With below logs from hub and the URL used is

http://192.168.39.45:31212/hub/login?next=

When I relaunch the jupyter from new browser window or tab the login happens without 500 : Internal Server Error. Or otherwise clicking the top left corner jupyterhub dashboard icon also brings back to login page and when I login from there it goes through without error.
"""
but I can't go through the 500:Internal Server Error after click login in.

**Comment by serlina** [comment]
@ mak-aravind, as you said several days ago
""""
@minrk With this fix # 1894, After bringing down postgres and resuming its service there are some observations I collated below :

when I open a browser and access the jupyterhub it immediately shows up a login page. For Dev I am using https://github.com/yuvipanda/jupyterhub-dummy-authenticator. When I login with a username its throwing 500: Internal Server Error. With below logs from hub and the URL used is

http://192.168.39.45:31212/hub/login?next=

When I relaunch the jupyter from new browser window or tab the login happens without 500 : Internal Server Error. Or otherwise clicking the top left corner jupyterhub dashboard icon also brings back to login page and when I login from there it goes through without error.
"""
but I can't go through the 500:Internal Server Error after click login in.

**Comment by minrk** [comment]
This seems like the most relevant piece of info:

> sqlalchemy.exc.ProgrammingError: (psycopg2.ProgrammingError) relation "users" does not exist
LINE 2: FROM users

That suggests that it's not a connection problem, but something wrong in the schema. Since this is a backported fix to a custom fork of jupyterhub, I don't really know how to help. My suspicion is that it is the backport itself that missed something. Since you only reference one commit, I will point out that this PR is more than one commit, just in case. You can see the whole patch [here](https://github.com/jupyterhub/jupyterhub/pull/1894.patch).

**Pull request merged**
