### PR TITLE
Update to simplify the language related to spawner options

### PR DESCRIPTION
**Pull request by NikeNano**
Fixes https://github.com/jupyterhub/jupyterhub/issues/2550

Changes:
1) Spawner options -> Server options
2) Spawn -> Start

### CODE REVIEW

**Comment by NikeNano** [comment]
R: @consideRatio

**Comment by consideRatio** [comment]
@minrk suggested https://github.com/jupyterhub/jupyterhub/issues/2550#issuecomment-490917109 "Server options" with lowercase O.

It is more pleasing to me, but I'm also conflicted about having buttons like "Shutdown Hub" And "Start My Server" as well. Even though there is also the "Request new API token" button without leading letter word capitalization.

This PR LGTM! Thanks for your initial feedback about the spawner view @NikeNano

**Comment by minrk** [comment]
Thanks! The lowercase O in my comment was a typo (from my phone). Title Case is what we want here, I think.

**Comment by consideRatio** [comment]
Wieeee thanks and congratulations on your first code contribution to JupyterHub @NikeNano ! :tada: :heart:

**Comment by NikeNano** [comment]
AWESOME! Thank you @consideRatio

**Pull request merged**
