### PR TITLE
Document use of pytest-asyncio in JupyterHub test suite

### LINKED ISSUE #4336: Documenting the current use of the `io_loop` fixture within JupyterHub's test suite
### Overview
Currently, the JupyterHub repository relies on the `io_loop` fixture to call coroutines. This is done using the `run_sync` method.

Given the current state of the `pytest-asyncio` plugin, that the JupyterHub test suite uses, we can now use top-level awaits to call coroutines within async functions.

*Example:*
```python
def example_function():
    server = io_loop.run_sync(get_server)
    return server
```
*would now be:*
```python
async example_function():
    server = await get_server()
    return server
```

### Proposed change

I believe it is important to document the current event-loop integration within JupyterHub using the `io_loop` fixture for anyone not familiar with it. 

It will also help guide the work of moving towards complete use of top-level awaits. Refer to [Min's PR](https://github.com/jupyterhub/jupyterhub/pull/4332) for a clear picture of what this work looks like.

Also, refer to this [Georgiana's issue](https://github.com/jupyterhub/pytest-jupyterhub/issues/30) that sparked the idea.

### PR DESCRIPTION
**Pull request by Sheila-nk**
- created a README file in the JupyterHub test suite that documents the use of the `pytest-asyncio` plugin
- included resources that provide additional information on `asyncio` and `event-loops`

Closes #4336

### CODE REVIEW

**Comment by Sheila-nk** [comment]
Ping @GeorgianaElena 
Please look at this draft PR and advise on changes I should make. Is this what we are aiming for?

**Comment by minrk** [comment]
This is great! But instead of a README, it should probably go in the contributing docs themselves. Those are easier to discover and read.

I think there are two kinds of documentation for JupyterHub tests, and two places they should go. The difference is based on who the reader is, and what kind of questions they may be trying to answer.

First is a contributor who wants to know how the tests work - maybe they are a Spawner author and are investigating how to write their own tests. Maybe they contributed a fix or feature and want to add test coverage. These folks want an _introduction_ to how JupyterHub tests work in general and what they need to know to write one. This kind of information should go in the contributing _documentation_ (in the new 'explanation' section, as reorganized by @alwasega). I think a new document there focused on writing and running tests makes sense.

Second is someone already working on tests, who want to understand what they are using. This kind of activity means they are reading code, and mostly this should be delivered via docstrings and comments in the fixtures and tests themselves.

**Comment by Sheila-nk** [comment]
Ping @alwasega 
Since you were reorganizing the contributing documentation, I think you would be the perfect person to tell me if the new additions make sense where they are. Or if there are changes that need to be made. Let me know what you think.
Thank you

**Comment by alwasega** [comment]
@Sheila-nk, I see we already have a section in the docs on [`Testing JupyterHub` ](https://jupyterhub.readthedocs.io/en/latest/contributing/tests.html#test-organisation). Does your doc complement what is there? If so, we can add it to this section.

**Comment by Sheila-nk** [comment]
> @Sheila-nk, I see we already have a section in the docs on [`Testing JupyterHub` ](https://jupyterhub.readthedocs.io/en/latest/contributing/tests.html#test-organisation). Does your doc complement what is there? If so, we can add it to this section.

Yes, it gives more information on these [fixtures](https://jupyterhub.readthedocs.io/en/latest/contributing/tests.html#test-organisation:~:text=io_loop%60%3A%20a,asyncio%20event%20loop) in particular and their significance and usage within the test suite. This will be helpful for anyone who wants to write tests.

**Comment by alwasega** [comment]
> Yes, it gives more information on these [fixtures](https://jupyterhub.readthedocs.io/en/latest/contributing/tests.html#test-organisation:~:text=io_loop%60%3A%20a,asyncio%20event%20loop) in particular and their significance and usage within the test suite. This will be helpful for anyone who wants to write tests.

In that case, and as suggested by @minrk, you could do a PR in the Contributions section of the docs to create a new document there. I will then group your new doc and the [Testing JupyterHub ](https://jupyterhub.readthedocs.io/en/latest/contributing/tests.html#test-organisation) file together in a separate PR.

**Comment by Sheila-nk** [comment]
@alwasega @minrk  I have created a new document `pytest-asyncio.md` within the contributing directory, I have not included it in any toctree though because I am not sure where it should appear in the documentation.

**Comment by alwasega** [comment]
@Sheila-nk, add it to the toctree in `contributing/index.md`. 

Screenshot 2023-02-10 at 12 36 13

**Comment by Sheila-nk** [comment]
> @Sheila-nk, add it to the toctree in `contributing/index.md`.

I was hesitant to add it there because it is related to testing which already has its own document. I hope I don't disturb the flow by doing that.

**Comment by alwasega** [comment]
I believe it should be okay. I will group the two together in a separate PR to enhance the overall readability and organization of the section.

**Comment by minrk** [comment]
@Sheila-nk can you add it as a _section_ (`### level 3 heading` under `## Test organisation`) in the `contributing/tests.md` file? We have some related information there already, this is more detail on the same topic.

**Comment by minrk** [comment]
Great, thanks @Sheila-nk, and thanks @alwasega for reviewing!

**Pull request merged**
