### PR TITLE
test postgres with url-encoded password

### PR DESCRIPTION
**Pull request by minrk**
to ensure this is handled correctly

seems to work (#2523)

### CODE REVIEW

**Comment by minrk** [comment]
@athornton this tests postgres with url-encoded password. Is there perhaps something not quite right in your URL in #2523?

**Comment by willingc** [comment]
@athornton Do you want to try to test this PR, if you have time, or would you prefer @minrk and I merge?

**Comment by athornton** [comment]
Just merge it, please.  If it's not working on my end, it could be a broken MySQL setup, or a bad design decision to store the whole connect string.  In any event I've worked around it for now and if it comes back to haunt me I'll give it a shot then.

**Comment by minrk** [comment]
@athornton thanks!

**Pull request merged**
