### PR TITLE
Fix user_row endblock in admin template

### PR DESCRIPTION
**Pull request by jtpio**
It looks like the `user_row` block was ended right after the `</tr>` element, while it is defined right after the corresponding `<tr>` element above:

https://github.com/jupyterhub/jupyterhub/blob/1f515464fe2edf5d9d8a7617c22ebe67002e0ba0/share/jupyterhub/templates/admin.html#L43-L46

This came up when trying to extend the admin template to add extra information to the user row.

### CODE REVIEW

**Comment by betatim** [comment]
cc @manics who I think did some work on making our docs build more strict. Maybe you have an idea why this comes up now and if the fix is easy. (The error message is not mega clear to me without opening the mentioned files etc)

**Comment by manics** [comment]
I only changed z2JH https://github.com/jupyterhub/zero-to-jupyterhub-k8s/pull/1611

A new major version of Sphinx (3.0.0) was released on 5 April https://pypi.org/project/Sphinx/3.0.0/ so perhaps it's gotten stricter?

**Comment by betatim** [comment]
https://www.sphinx-doc.org/en/master/changes.html I can spy anything obvious in the change log :-/

**Comment by jtpio** [comment]
> `use :noindex: for one of them`

Maybe we could try that? (from the error message)

**Comment by rkdarst** [comment]
We found a little bit more here: https://github.com/jupyterhub/jupyterhub/pull/2726 (I guess we should make a new issue about it...)

**Comment by betatim** [comment]
Oh wow, I clicked the "update branch" button the GitHub UI in order to find out what it does...turns out the button doesn't ask for confirmation it just does its thing. This is how we got `master` merged into this branch. I had originally planned to rebase this branch on latest master to see if that fixes the builds. (merge master into this branch has AFAIK the same effect as rebasing just less pretty)

Let's see what happens.

**Comment by betatim** [comment]
All the robots are happy, so merging this. Thanks for the patience and to all those who helped debugging things.

**Comment by jtpio** [comment]
Thanks!

**Pull request merged**
