### PR TITLE
Update gallery-jhub-deployments.md

### PR DESCRIPTION
**Pull request by LexiJess**
Added Sirepo to the gallery of deployments--the update is showing in the repo, but not on the live site. I've cleared the cache, checked on a different network connections, etc. but the change is not reflected. Any help is appreciated!

### CODE REVIEW

**Comment by consideRatio** [comment]
This PR added a space, then our autoformatting removed it - I'm closing it.

**Comment by LexiJess** [comment]
I'm pinging this again--the update made to the GH repo isn't reflected in the live site. Can anyone offer insight into why? Thanks!

**Comment by consideRatio** [comment]
This pull request didn't change anything and wasn't approved / merged to the main branch - what did you intend to add?

**Comment by minrk** [comment]
You can find the latest build of the docs with this link [here](https://jupyterhub.readthedocs.io/en/latest/reference/gallery-jhub-deployments.html#sirepo)

**Pull request closed without merging**
