### PR TITLE
add python 3.7 to travis

### PR DESCRIPTION
**Pull request by willingc**

### CODE REVIEW

**Comment by betatim** [comment]
Looks like Travis don't support 3.7 yet? Their docs mention 3.7-dev. Do you know if this will change soon, if yes let's keep this PR open and merge it as soon as 3.7 support is there.

**Comment by willingc** [comment]
@betatim That's cool. Python 3.7 was released today so hopefully Travis will support soon.

**Comment by minrk** [comment]
I learned from digging through travis that if we add:

```
dist: xenial
sudo: true
```

then `python: 3.7` will work. It's not available for the `trusty` image yet, though.

**Comment by minrk** [comment]
Picking up xenial worked for me on pyzmq: https://github.com/zeromq/pyzmq/pull/1185/commits/603bafd2112ca8671569eb7ef5bb42e2a1a15a2a

**Comment by willingc** [comment]
Removed the test env in the last commit and it passes. Unfortunately, it does fail when the env is present.

**Pull request merged**
