### PR TITLE
Use jupyterhub repository_owner in registry-overviews

### PR DESCRIPTION
**Pull request by mathbunnyru**
Follow-up on: https://github.com/jupyterhub/jupyterhub/pull/4634/

### CODE REVIEW

**Comment by mathbunnyru** [comment]
@minrk sorry, I didn't change `jupyter` -> `jupyterhub`.

**Comment by minrk** [comment]
Thanks!

**Comment by mathbunnyru** [comment]
@minrk we need to create new access token with `Read, Write, Delete` permission and then use it here.
Could you do that please?
I have no permissions in `jupyterhub` Docker Hub / GitHub.

**Comment by minrk** [comment]
Apparently, it needs full admin permissions to edit the readme, including permanently deleting the repo! I don't really want the bot to have that level of permission. Is that the only way?

**Comment by minrk** [comment]
Got it. Updated permissions and re-ran the action. All green!

**Comment by mathbunnyru** [comment]
Great, seems to work 👍

**Pull request merged**
