### PR TITLE
Display Sphinx linkcheck output in a more readable format

### PR DESCRIPTION
**Pull request by manics**
I've copied https://github.com/jupyterhub/zero-to-jupyterhub-k8s/blob/77e9df64f926582417ce8389cc55d58849ce4aff/ci/summarise-linkcheck-output#L1-L23 into an action:
https://github.com/manics/action-sphinx-linkcheck-summary

Example output:
image

Without this PR:
image

### CODE REVIEW

**Comment by minrk** [comment]
That's awesome!

The CURC link in the gallery should be removed, since that's apparently been shut down.

The pyspark doc link is _wildly_ out of date, and no similar page seems to exist in the current docs. We could just remove the `pySpark configuration documentation` link sentence. We could link to [SparkConf](https://spark.apache.org/docs/3.5.2/api/python/reference/api/pyspark.SparkConf.html?highlight=sparkconf#pyspark.SparkConf) via intersphinx, or we could even remove the spark executor faq entry entirely, since I'm not sure how f that q is a'd these days.

**Comment by minrk** [comment]
Removed the broken links in #4883

**Review by minrk — APPROVED** [review]

**Comment by minrk** [comment]
@manics not merging because this is a draft, but it's not clear what more you want to do here. It seems great, already!

**Comment by manics** [comment]
Thanks! I was going to tag the action and discuss whether it should be moved to the JupyterHub GitHub org, but given I haven't done anything I'll merge and return to it later.

**Pull request merged**
