### PR TITLE
[wip] Idle culling implementation using notebook activity data

### PR DESCRIPTION
**Pull request by angelikamukhina**
https://github.com/jupyterhub/outreachy/issues/25

### CODE REVIEW

**Comment by minrk** [comment]
@gweis both true! I'm hoping to fix the first with oauth scopes so that a token for idle culling could have access to read activity without write access to the notebook api. The second I've been meaning to get to for some time, and should be improved by https://github.com/jupyter/notebook/pull/4235

**Comment by gweis** [comment]
@minrk Awesome,... looking forward for these changes to be released ;). These would really help to track activity in notebooks (not just user activity, but also active / running cells / kernels etc...)

**Comment by consideRatio** [comment]
Stil PR has been stale for a long time it seems, and I know that there is now a dedicated package that does culling. @angelikamukhina and @minrk, any suggestions on what to do at this point with this PR?

**Comment by yuvipanda** [comment]
I think we can close this now. Thanks for getting this going, @angelikamukhina.

**Pull request closed without merging**
