### PR TITLE
Issue #13 Outreachy: add running_servers metric

### PR DESCRIPTION
**Pull request by GeorgianaElena**

### CODE REVIEW

**Comment by minrk** [comment]
Thanks for the PR! Can we call the metric ''running_servers' instead of 'currently_running_servers'? The 'currently' part is already implied by the fact that it's a metric. Otherwise, 👍!

**Comment by GeorgianaElena** [comment]
Hi Min! I've updated the pull request, thanks a lot for the feedback!

**Comment by minrk** [comment]
@GeorgianaElena thank you!

**Comment by minrk** [comment]
Congratulations on your first PR to JupyterHub! Welcome!

**Pull request merged**
