### PR TITLE
ci: update black configuration

### PR DESCRIPTION
**Pull request by consideRatio**

### CODE REVIEW

**Comment by manics** [comment]
What does this do? Does it make sense to target more than one python version?

**Comment by consideRatio** [comment]
Apparently its meant to list all versions one wants to ve compatible against. It is confusing indeed, forgot where i read it. This just updates some references not knowing if it matters, but it seems it didnt.

**Comment by manics** [comment]
Oh well... Maybe add a comment saying it's a mystery (or something more sensible 😀) and merge if it's no harm?

**Comment by consideRatio** [comment]
@manics done!

**Comment by minrk** [comment]
I had no idea, thanks!

**Pull request merged**
