### PR TITLE
Improve help comments for SSL key/certs configuration parameters

### PR DESCRIPTION
**Pull request by stuartcampbell**
The "Use with ssl_key" and "Use with ssl_cert" were just in the wrong sections.

### CODE REVIEW

**Comment by minrk** [comment]
I think this is backwards. The comments are supposed to be saying that "ssl_key should be used with ssl_cert" and vice versa. With this PR, the help strings are saying that 'ssl_key should be used with ssl_key', which is not what we want.

We could propbably communicate that more clearly, though. Do you want to take a stab at updating these help strings to signal that when setting each one, you should also set the other?

**Comment by stuartcampbell** [comment]
Ah I see now, yes I'll have a crack at it

**Comment by stuartcampbell** [comment]
How's this ?

**Comment by minrk** [comment]
Perfect, thank you!

**Pull request merged**
