### PR TITLE
Using python3 doesn't work on most windows python installations even …

### PR DESCRIPTION
**Pull request by softkeldozy**
…when having dual installation but instead using just python works all the time

### CODE REVIEW

**Comment by manics** [comment]
Hi! Please could you explain a bit more about this change? Windows doesn't come with Python, so whether `python` or `python3` works will depend on how it's installed.

**Comment by softkeldozy** [comment]
Yes, windows don't come with python, but there are times when using python3 throws an error.
I recently worked on a Django project where I have about 5 Windows 10 Pro Pc (including mine), all having python installed, and that command didn't work. But when I used just python, it worked.
In my case, I had 2 versions installed on my Pc, and that command didn't work either. So I had to uninstall both, did a clean installation. Next, I ran python3 still nothing, so I just used python, and it worked perfectly. My colleagues had the same issue recently, and running python fixed it.

**Comment by minrk** [comment]
How did you install Python? Every Windows Python install I have, `python3` works.

Windows is also not supported by JupyterHub, so I'm not sure a Windows-specific caveat that affects _some_ Windows Python environments to basic install docs is appropriate.

**Comment by minrk** [comment]
Thanks for your contribution! I'm going to close this, since the statement it adds about "doesn't work on most Windows" is not correct, and unusual Windows caveats aren't appropriate for top-level docs in a project that doesn't support Windows.

**Pull request closed without merging**
